[package]
name = "peer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_bencode = "0.2.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_bytes = "0.11"
sha1 = "0.10.1"
hex = "0.4.3"
